#!/bin/bash

echo "🔧 Recipe Finder - Complete Jenkins Fix"
echo "======================================"

echo "📋 Current Git status:"
git status --short

echo ""
echo "🌿 Current branch:"
git branch

echo ""
echo "📝 Jenkins Pipeline Fix Instructions:"
echo "====================================="
echo ""
echo "The issue is that Jenkins container doesn't have Node.js/npm/Docker installed"
echo "and the workspace is empty. Here are the solutions:"
echo ""
echo "🎯 SOLUTION 1 (Recommended - Docker-only approach):"
echo "=================================================="
echo "1. Go to Jenkins: http://localhost:8080"
echo "2. Open your job: recipe-finder-deployment"
echo "3. Click 'Configure'"
echo "4. In Pipeline section:"
echo "   - Definition: Pipeline script"
echo "   - Script: Copy contents from Jenkinsfile.docker"
echo "5. Save and run the build"
echo ""
echo "🎯 SOLUTION 2 (Git SCM approach):"
echo "================================"
echo "1. Go to Jenkins: http://localhost:8080"
echo "2. Open your job: recipe-finder-deployment"
echo "3. Click 'Configure'"
echo "4. In Pipeline section:"
echo "   - Definition: Pipeline script from SCM"
echo "   - SCM: Git"
echo "   - Repository URL: $(pwd)"
echo "   - Branch Specifier: */main"
echo "   - Script Path: Jenkinsfile.git"
echo "5. Save and run the build"
echo ""
echo "🎯 SOLUTION 3 (Install tools in Jenkins):"
echo "========================================"
echo "If you want to install Node.js and Docker in Jenkins:"
echo "1. Go to Manage Jenkins > Manage Plugins"
echo "2. Install 'NodeJS Plugin' and 'Docker Plugin'"
echo "3. Go to Manage Jenkins > Global Tool Configuration"
echo "4. Configure NodeJS and Docker installations"
echo ""
echo "🚀 What the pipeline will do:"
echo "   ✅ Checkout code (if using Git SCM)"
echo "   ✅ Build Docker image (handles npm install/build)"
echo "   ✅ Test the Docker image"
echo "   ✅ Deploy to http://localhost:3000"
echo ""
echo "💡 The Docker approach is recommended because:"
echo "   - No need to install tools in Jenkins"
echo "   - Consistent build environment"
echo "   - Handles all dependencies automatically"
