#!/bin/bash

echo "🔧 Recipe Finder - Jenkins GitHub Fix"
echo "===================================="

echo "✅ Fixed Jenkinsfile pushed to GitHub!"
echo ""
echo "📝 Next steps to fix your Jenkins pipeline:"
echo "=========================================="
echo ""
echo "1. Go to Jenkins: http://localhost:8080"
echo "2. Open your job: recipe-finder-deployment"
echo "3. Click 'Configure'"
echo "4. In Pipeline section, verify:"
echo "   - Definition: Pipeline script from SCM"
echo "   - SCM: Git"
echo "   - Repository URL: https://github.com/VivekKamble014/Recipe-Finder.git"
echo "   - Branch Specifier: */main"
echo "   - Script Path: Jenkinsfile"
echo "5. Click 'Save'"
echo "6. Click 'Build Now'"
echo ""
echo "🎯 What the fixed pipeline will do:"
echo "   ✅ Checkout code from GitHub"
echo "   ✅ Build Docker image (if Docker available)"
echo "   ✅ Test the Docker image"
echo "   ✅ Deploy to http://localhost:3000"
echo ""
echo "🔧 If Docker is not available in Jenkins:"
echo "   - Use Jenkinsfile.no-docker instead"
echo "   - It will fallback to npm serve"
echo ""
echo "🚀 The pipeline should now work without the kubernetes agent error!"
