#!/bin/bash

echo "🔧 Recipe Finder - Jenkins NPMRC Fix"
echo "===================================="

echo "✅ Fixed Jenkinsfile to handle custom npm registry!"
echo ""
echo "🎯 The issue was:"
echo "   ❌ npm trying to connect to local Nexus at localhost:8081"
echo "   ❌ Nexus service not running in Jenkins environment"
echo "   ❌ ECONNREFUSED error when trying to fetch eslint"
echo ""
echo "🔧 The solution:"
echo "   ✅ Temporarily backup .npmrc during Jenkins build"
echo "   ✅ Use default npm registry (npmjs.com) for dependencies"
echo "   ✅ Restore .npmrc after build completes"
echo ""
echo "📝 Next steps:"
echo "1. Go to Jenkins: http://localhost:8080"
echo "2. Open your job: recipe-finder-deployment"
echo "3. Click 'Build Now'"
echo "4. Monitor the build progress"
echo ""
echo "🚀 The pipeline will now:"
echo "   ✅ Install Node.js using nvm"
echo "   ✅ Backup .npmrc to avoid Nexus connection issues"
echo "   ✅ Install dependencies from default npm registry"
echo "   ✅ Run ESLint using npx"
echo "   ✅ Build React app using npx"
echo "   ✅ Deploy using npm serve on port 3000"
echo "   ✅ Restore .npmrc after build"
echo ""
echo "🔍 After successful build:"
echo "   - Application: http://localhost:3000"
echo "   - Logs: /tmp/recipe-finder.log"
echo ""
echo "🎉 This should now work without Nexus connection errors!"
echo ""
echo "💡 Key fix: Temporarily disable custom registry during build"
echo "   to avoid connection issues with local Nexus service."
